### ISSUE TITLE
MDC101 - cannot be build using macOS. 

### ISSUE THREAD

**Issue by thegayankalinga** [material-components/material-components-web-codelabs#213]
Getting many errors and server is not starting. in the mac os

**Comment by ntdaley** [comment]
I am also unable to build MDC 101 on Mac OS X.

I am running MacOS Mojave v10.14.6
I am running nodejs v15.5.0 (installed via homebrew)

I get errors when running `npm install`
I have attached the npm log.

It looks like it happens while installing the dependency 'fibers'... 
May be related to [their issue 424](https://github.com/laverdet/node-fibers/issues/424)


[2021-01-17T01_39_01_297Z-debug.log](https://github.com/material-components/material-components-web-codelabs/files/5825406/2021-01-17T01_39_01_297Z-debug.log)

**Comment by thegayankalinga** [comment]
what i did is install fibers globally 
 `sudo npm install -g fibers `

Then i changed the package.json file in the mdc101 starter folder to update to v5 of the fibers
`"fibers": "^5.0.0",` 

then i redo the `npm install`
still the errors come

however this time i can start the localhost:8080 server with `npm start`

Why is this issue cannot be solvable by the material web dev team. It is very easy to recreate using a mac..

Can someone kindly help here pls.

**Comment by marko7460** [comment]
I have the similar issues with mdc101
Mac OS Catalina
```
14:20 $ npm install

> fsevents@1.2.7 install /Users/marko/Tutorials/Material/material-components-web-codelabs/mdc-101/starter/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.7 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2722:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
...
...
...
5 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/marko/Tutorials/Material/material-components-web-codelabs/mdc-101/starter/node_modules/fibers
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

I tried https://github.com/fsevents/fsevents/issues/278#issuecomment-538449044 and it worked for me
```
 rm -rf package-lock.json 
 rm -rf node_modules/
 npm install
 npm audit fix
```
