### ISSUE TITLE
[codelab] Error: Couldn't find preset "react-native" relative to directory

### ISSUE THREAD

**Issue by WebRuin** [material-components/material-components-web-codelabs#26]
After cloning `https://github.com/material-components/material-components-web-codelabs`, the initial `npm i` and `npm start`, yields the following:

`ERROR in (webpack)-dev-server/client?http://localhost:8080
    Module build failed: Error: Couldn't find preset "react-native" relative to directory "/home/tithos/Learning/Web"
        at /home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (<anonymous>)
        at OptionManager.resolvePresets (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-loader/lib/index.js:50:20)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js

    ERROR in ./app.js
    Module build failed: Error: Couldn't find preset "react-native" relative to directory "/home/tithos/Learning/Web"
        at /home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (<anonymous>)
        at OptionManager.resolvePresets (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/home/tithos/Learning/Web/material-components-web-codelabs/mdc-101/starter/node_modules/babel-loader/lib/index.js:50:20)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js`

I am running `node -v v10.0.0` and `npm -v 6.0.1` on Ubuntu 18

**Comment by kfranqueiro** [comment]
Just to confirm, you're experiencing this straight out of the box with no alterations to mdc-101/starter, just running `npm i` then `npm start`?

I tried to repro this with node 10.1.0 and npm 6.0.1 but haven't encountered this error. Could you also provide the output of `npm ls --depth 1`?

The one other thing I find odd is that it is looking relative to a directory that is several levels above the `starter` directory. Can you confirm you are running these commands from within the `starter` directory?

It sounds like this issue and #25 are probably similar, and it'd certainly be good to figure out what's causing people to run into this situation.

**Comment by WebRuin** [comment]
➜  starter git:(master) ✗ npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 9.368s
[!] 13 vulnerabilities found [6901 packages audited]
    Severity: 3 Low | 10 Moderate
    Run `npm audit` for more detail

**Comment by kfranqueiro** [comment]
I just ran `npm i` within the `mdc-103/starter` directory and got the same results from `npm ls --depth 1` as yours. However, I don't encounter any issues running `npm start`. Do you still encounter the issue within the `mdc-103/starter` directory? (I got the impression from your original post that you may have been running from a parent directory.)

Nothing within the source code of the MDC Web codelabs references the react-native preset (we only reference es2015, which is listed in our package.json), so I'm wondering if it's somehow possible that some other webpack config was getting loaded?

**Comment by kfranqueiro** [comment]
Since we haven't been able to reproduce this, and haven't heard anything back, I'm going to close this. If you continue to have this issue, I'd suggest starting clean by re-extracting the source from this repo into an empty folder that has no pre-existing webpack configuration in or above it.
