### ISSUE TITLE
[codelab] MDC-101 Web: Material Components (MDC) Basics (Web)

### ISSUE THREAD

**Issue by lesolorzanov** [material-components/material-components-web-codelabs#292]
Just in the beginning when startig with mdc-101 I get
```

> mdc-101-web@0.0.0 start
> webpack-dev-server --progress

sh: 1: webpack-dev-server: not found

```

Then I installed   `sudo npm install webpack-dev-server -g` and get
```
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}

```
What should I do?

**Comment by vijaynyaya** [comment]
Notice: `Error: Cannot find module 'webpack-cli/bin/config-yargs'` 
It requires webpack-cli to work.  Do: `npm i -D webpack-cli`
