### ISSUE TITLE
install breaks

### ISSUE THREAD

**Issue by koaning** [material-components/material-components-web-codelabs#76]
because of my local system python being python3.7 it seems that node cannot install certain packages that are part of the 101 tutorial found [here](https://codelabs.developers.google.com/codelabs/mdc-101-web/#1). 

```
> npm install 
...
gyp verb check python version `/Users/vincent/miniconda3/bin/python -c "import platform; print(platform.python_version());"` returned: "3.7.0\n"
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/vincent/miniconda3/bin/python" is v3.7.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/vincent/Development/material-components-web-codelabs/mdc-101/starter/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/vincent/Development/material-components-web-codelabs/mdc-101/starter/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:285:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:395:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:616:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/Users/vincent/Development/material-components-web-codelabs/mdc-101/starter/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/vincent/Development/material-components-web-codelabs/mdc-101/starter/node_modules/node-sass
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
```

I am totally new to `node` and I am having trouble seeing an obvious way to fix.

**Comment by koaning** [comment]
same issue it seems. 

```
➜  material-components-web-codelabs-master cd mdc-101/starter
➜  starter ls
_common.scss      home.js           login.js          package.json
assets            home.scss         login.scss        webpack.config.js
home.html         index.html        package-lock.json
➜  starter npm install

> fsevents@1.2.4 install /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.2.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/vincent/miniconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:395:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:616:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.2.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents
node-pre-gyp ERR! node -v v11.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/11.2.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi' (1)

> node-sass@4.9.0 install /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/darwin-x64-67_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.0 postinstall /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/11.2.0/bin/node /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/Cellar/node/11.2.0/bin/node',
gyp verb cli   '/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@11.2.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:161:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:13:12)\n    at F (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:68:19)\n    at E (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:80:29)\n    at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/which/which.js:89:16\n    at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/isexe/index.js:42:5\n    at /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/isexe/mode.js:8:5\n    at FSReqCallback.oncomplete (fs.js:161:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /Users/vincent/miniconda3/bin/python
gyp verb check python version `/Users/vincent/miniconda3/bin/python -c "import platform; print(platform.python_version());"` returned: "3.7.0\n"
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/vincent/miniconda3/bin/python" is v3.7.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:285:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:395:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:616:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/11.2.0/bin/node" "/Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/vincent/Downloads/material-components-web-codelabs-master/mdc-101/starter/node_modules/node-sass
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincent/.npm/_logs/2018-12-08T09_49_55_828Z-debug.log
```

**Comment by kfranqueiro** [comment]
FYI something like [pyenv](https://github.com/pyenv/pyenv) might help if you need to juggle python versions.

**Comment by kfranqueiro** [comment]
Even without node-sass in the dependencies, fsevents also typically requires building. fsevents is required by webpack-dev-server, which is an integral part of running the codelabs, so this isn't something we're likely to avoid. Unfortunately python 2 is required for gyp (and thus node-gyp) to function.

Closing this since we're unable to fix from our end.
